import = [
"~/.config/alacritty/local.toml",
"~/.config/alacritty/theme.toml",
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

[window]
decorations = "none"
